# Disable running all jobs on startup
spring.batch.job.enabled = false

# Init Spring core Schema
spring.batch.jdbc.initialize-schema=always

# Create custom table and init data
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:createTable.sql
# spring.sql.init.data-locations=classpath:initData.sql