# Disable running all jobs on startup
spring.batch.job.enabled = false

# Turn off metadata db auto creation
# spring.batch.initializer.enabled = false

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:initDB.sql